<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<RootNamespace>MECCG_Deck_Builder</RootNamespace>
		<UseWindowsForms>true</UseWindowsForms>
		<Platforms>AnyCPU;x86</Platforms>
		<ApplicationIcon>MECCGicon.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="MECCGicon.ico" />
		<None Remove="Resources\Help\MECCG_Deck_Builder.chm" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="MECCGicon.ico" />
		<Content Include="Resources\Help\MECCG_Deck_Builder.chm">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="MECCGicon.ico" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="NaturalSort.Extension" Version="4.4.1" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="8.0.1" />
		<PackageReference Include="System.Text.Encoding.CodePages" Version="8.0.0" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Properties\Resources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Properties\Resources.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

</Project>